version: '3.7'

services:
  app-server:
    build:
      context: jumia-app-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always

    networks:
      - backend
      - frontend

  app-client:
    build:
      context: jumia-app-client
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend

volumes:
  db-data:

networks:
  backend:
  frontend: